[build]
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/rom.gba"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=86400"
